### ISSUE TITLE
Make a good header

### ISSUE THREAD

**Issue by lakshyatyagi24** [StudentCode-in/Scodex#8]
Need to improve CSS of header

**Comment by jonamooney** [comment]
This would be my first issue. I'd like to give it a shot.

**Comment by lakshyatyagi24** [comment]
Sure @jonamooney you can fork this repo and star this repo then you can start working on it make a pull request team will review you work and merge it

**Comment by jonamooney** [comment]
Thanks @lakshyatyagi24 I want to make sure that I am on the right track. Is this issue to "clean up" or fix the css for the site's header or are you looking for a design change for the header?

**Comment by lakshyatyagi24** [comment]
better if we will re-design a better header for website

**Comment by jonamooney** [comment]
Great! Thanks.

**Comment by jonamooney** [comment]
@lakshyatyagi24 I made a few changes to the header and submitted a pull request. Please let me know if I completed this whole process correctly. I can also make additional changes. Thanks.
